vich_uploader:
    db_driver: orm

    mappings:
        media_object:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/public/media'
            # Renommera les fichiers téléchargés en utilisant un identifiant unique comme préfixe.
            namer: Vich\UploaderBundle\Naming\OrignameNamer